version: '3.8'

services:
  api:
    build: .
    container_name: sales-order-api-container
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://username:password@db:5432/sales_db
    networks:
      - my_network

  db:
    image: postgres:13
    container_name: postgres-container
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=sales_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - my_network

volumes:
  pg_data:

networks:
  my_network:
